### PR TITLE
login button fix

### PR DESCRIPTION
**Pull request by Atimabh**
Fixed the login button screen shake bug

### CODE REVIEW

**Comment by Atimabh** [comment]
@KushalBhanot Please review my code, thank you.

**Comment by 20Koen02** [comment]
Sigh.

**Comment by KushalBhanot** [comment]
Hey, @Atimabh!

Please provide a description of what changes you made.

**Comment by Atimabh** [comment]
Hi, @KushalBhanot 

Earlier the page used to shake upon hovering on the Login button, the issue was that there was a border property on that button of 1px and upon hover the border width was being reduced to 0px which caused the page to shake so I fixed it by making the border width constant of 1px both normally and upon hovering.

**Comment by KushalBhanot** [comment]
okay, @Atimabh! Thanks for contributing to our repo 👍🏻

**Pull request merged**
