### PR TITLE
Link btn fix

### PR DESCRIPTION
**Pull request by lukes-code**
Link btn fix for issue

### CODE REVIEW

**Comment by KushalBhanot** [comment]
Hey, @lukes-code!

Kindly, raise an issue before making a PR. Currently, there exists no issue corresponding to your PR. By no means, I'm demotivating you. All I'm saying is making good PRs and add/fix features.

Best,
Kushal

**Comment by KushalBhanot** [comment]
The issue which you resolved is not the same as I asked. I was referring to href links in the navbar in the issue. It looks like you confused it with navbar buttons.

**Comment by lukes-code** [comment]
Hi @KushalBhanot this was for the issue "Fix navlinks across the HTML pages"

**Comment by KushalBhanot** [comment]
I'm sorry @lukes-code, if there was some understanding mistake on my end. I have edited the issue. Go ahead and make the changes and I'll merge them :)

**Comment by lukes-code** [comment]
No problem at all! How can I re-open the merge or should I submit another?

**Comment by KushalBhanot** [comment]
I reopened this PR. Go ahead with your work 😊🙌🏻

**Comment by lukes-code** [comment]
thanks @KushalBhanot the change is in the PR. The commit for styles.css

**Comment by KushalBhanot** [comment]
Check it again. The changes are not complete and remove any CSS changes that you made earlier.

**Pull request merged**
