### PR TITLE
feat: update style of jobs and resources

### PR DESCRIPTION
**Pull request by MaximeKoitsalu**
Hey Kushal, I updated the style of the resource page for jobs and scholarships. Feel free to give feedback if you want me to change anything. I saw you missed some closing tags here and there as well as the closing `</footer>` tag.

### CODE REVIEW

**Comment by KushalBhanot** [comment]
The design looks good. But I think you're missing something. The page is not responsive in mobile view. And the tags you're talking about are `self-closing`, except the footer tag. I don't mean to demotivate you. All I'm saying is I expect good PR from you. 

Also, make sure there's no overflow in the x-axis.

Add changes to this PR and I'll merge after there are no conflicts. Fair?

**Comment by MaximeKoitsalu** [comment]
No worries at all all @KushalBhanot I'm here to help you 👍 , I'll take a look again and fix your feedback.

**Comment by MaximeKoitsalu** [comment]
@KushalBhanot Hey, think I got it this time. Hope it is to your liking. Tried making it look a bit more like the landing page :)

**Comment by KushalBhanot** [comment]
There's still overflow in the x-direction. If you would inspect the home page closely, you would notice that I changed the color of the title to make it more visible on the black opacity background. So, don't make any changes to the intro-div.

Just fix the overflow and revert the changes of the first intro-div and I'll merge them.

**Comment by MaximeKoitsalu** [comment]
I have fixed the overflow. Regarding the color of the `<h1>` element in the page. It follows the same logic as the one on the landing page. `color: #EF6700;` on normal screen and `color: orange;` on mobile against the darker backdrop `::before` element. 

Are you saying you don't want the color to change depending on the background color of the text?

**Comment by KushalBhanot** [comment]
Everything's fine now. I'm happy with the changes. Nice work, @MaximeKoitsalu!

**Pull request merged**
